server:
  port: 8080

spring:
# 数据源配置
  datasource:
     url: jdbc:mysql://39.104.160.80:3306/guoyan?characterEncoding=UTF-8
     username: gydb
     password: gy123456
     driver-class-name: com.mysql.jdbc.Driver

# redis 配置
#  redis:
#    host: 47.94.108.128
#    password: sang123456
#    port: 6379

mybatis:
   # mybatis.config= classpath:mybatis-config.xml
   mapperLocations: classpath:mappers/*.xml
   # domain object's package
   typeAliasesPackage: cn.xdc.bean


